/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danielczykjakub_projekt;

import java.awt.Graphics;
import java.awt.event.KeyEvent;


/**
 *
 * @author JakubDanielczyk
 */
public class GamePanel extends javax.swing.JPanel {

    private Car car;
    private PoliceCar policeCar;
    private Road road;
    private boolean spacePressed = false;
    
    public GamePanel() {
        initComponents();
        setFocusable(true);
        car = new Car();
        policeCar = new PoliceCar();
        road = new Road();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            System.out.println("Spacja");
            spacePressed = true;
            startGame();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            car.moveLeft();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            car.moveRight();
        }
    }//GEN-LAST:event_formKeyPressed

    
    private void startGame() {
        add(car);
        add(policeCar);
        add(road);
        road.prepareStripes();
        revalidate();
        repaint();
        road.startTimers();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (!spacePressed) {
            g.drawString("PRESS SPACE TO START PLAYING", 100, 150);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
