/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danielczykjakub_projekt;

import javax.swing.JFrame;

/**
 *
 * @author JakubDanielczyk
 */
public class MenuPanel extends javax.swing.JPanel {

    private MainWindow parentFrame;
    
    public MenuPanel(MainWindow parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        highScoreTextLabel = new javax.swing.JLabel();
        highScoreLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(150, 100, 160));

        titleLabel.setFont(new java.awt.Font("Noteworthy", 3, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Police Escaper");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        startButton.setText("Start Game");
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        highScoreTextLabel.setFont(new java.awt.Font("Marker Felt", 3, 18)); // NOI18N
        highScoreTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreTextLabel.setText("High Score:");

        highScoreLabel.setFont(new java.awt.Font("Marker Felt", 3, 18)); // NOI18N
        highScoreLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(startButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(highScoreTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highScoreLabel))
                            .addComponent(titleLabel))))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(titleLabel)
                .addGap(133, 133, 133)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highScoreTextLabel)
                    .addComponent(highScoreLabel))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        GamePanel gamePanel = new GamePanel();
        parentFrame.setContentPane(gamePanel);
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highScoreLabel;
    private javax.swing.JLabel highScoreTextLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
